import { Component, OnInit } from '@angular/core';

@Component({
  selector: "app-not-found-page",
  templateUrl: "./not-found-page.component.html",
  styleUrls: ["./not-found-page.component.css"],
})
/*
 * Controls View of Not Found Page: Angular Autogenerated class
 * @class
 * @implements { OnInit }
 */
export class NotFoundPageComponent implements OnInit {
  /**
   * Creates the NotFoundPageComponent class
   * @constructor
   */
  constructor() {}

  /**
   * Loads any scripts needed for Not Found Page
   */
  ngOnInit(): void {}
}
