import { Component, OnInit } from '@angular/core';

@Component({
  selector: "app-about-page",
  templateUrl: "./about-page.component.html",
  styleUrls: ["./about-page.component.css"],
})

/**
 * Controls View of About Page: Angular Autogenerated class
 * @class
 * @implements { OnInit }
 */
export class AboutPageComponent implements OnInit {
  /**
   * Creates the AboutPageComponent class
   * @constructor
   */
  constructor() {}

  /**
   * Loads any scripts needed for About Page
   */
  ngOnInit(): void {}
}
