import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
/**
 * Controls view of main app: Angular Autogenerated class
 * @class
 */
export class AppComponent {
  title = 'SendableCompSci';
}
