import { Component, OnInit } from '@angular/core';

@Component({
  selector: "app-email-upload",
  templateUrl: "./email-upload.component.html",
  styleUrls: ["./email-upload.component.css"],
})
/**
 * Controls View of Email Upload Page: Angular Autogenerated class
 * @class
 * @implements { OnInit }
 */
export class EmailUploadComponent implements OnInit {
  /**
   * Creates the EmailUploadComponent class
   * @constructor
   */
  constructor() {}

  /**
   * Loads any scripts needed for Email Upload Page
   */
  ngOnInit(): void {}
}
